export const question = [
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/1.jpg"),
    question: "Zostawiłeś na stole ulubione ciasteczko- czy kot je zje?",
    answer1: "Kot nie połakomił się na nie.",
    answer2: "Kot zjadł całe ciasteczko.",
    answer3: "To zależy od rasy Kota.",
    buttonText: "Następne pytanie",
    quriosity:
      "Koty nie odczuwają słodkiego smaku, dlatego są to dla nich tylko puste kalorie.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/2.jpg"),
    question: "Czym pocą się koty?",
    answer1: "Główką",
    answer2: "Łapkami",
    answer3: "Całym ciałem",
    buttonText: "Następne pytanie",
    quriosity:
      "Gruczoły potowe u kota znajdują się na poduszkach łapek. Koty pocą się nie tylko w celu wyrównania temperatury ciała, ale także gdy są niespokojne.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/3.jpg"),
    question: "Czy uszy kota są obrotowe?",
    answer1: "Tak, o 180 stopni",
    answer2: "Tak, o 90 stopni",
    answer3: "Nie",
    buttonText: "Następne pytanie",
    quriosity:
      "Kot potrafi obrócić swoje ucho aż o 180 stopni. Uszy u kota są również sposobem na wychwycenie jego zmiany nastroju.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/4.jpg"),
    question: "Czy istnieją koty lewo-łapne?",
    answer1: "Tak, ale tylko Kotki.",
    answer2: "Nie.",
    answer3: "Tak, ale tylko kocury.",
    buttonText: "Następne pytanie",
    quriosity:
      "Według badań, kotki wykazują tendencję do bycia prawo- łapne, a kocury lewo-łapne.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/5.jpg"),
    question: "Ile różnych dźwięków są w stanie wydać koty?",
    answer1: "Ponad 50.",
    answer2: "Ponad 100.",
    answer3: "Ponad 150.",
    buttonText: "Następne pytanie",
    quriosity: "Psy mogą natomiast wydawać tylko około 10.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/6.jpg"),
    question: "Kto lepiej słyszy?",
    answer1: "Pies",
    answer2: "Kot",
    answer3: "Zarówno pies i kot słyszą tak samo",
    buttonText: "Następne pytanie",
    quriosity:
      "Kot jest w stanie także wychwytywać dźwięki o częstotliwości wyższej niż człowiek.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/7.jpg"),
    question: "Ile kosztował najdroższy kot na świecie?",
    answer1: "około 50 tys.",
    answer2: "około 100 tys.",
    answer3: "około 150 tys.",
    buttonText: "Następne pytanie",
    quriosity:
      "Był to kot Little Nicky i był pierwszym sklonowanym kotem na zamówienie.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/8.jpg"),
    question: "Czy koty mają unikalne linie papilarne?",
    answer1: "Tak",
    answer2: "Nie",
    answer3: "Tylko niektóre",
    buttonText: "Następne pytanie",
    quriosity:
      "Okazuje się, że nie można znaleźć dwóch kotów o identycznym nosie. Co więcej koty swojego nosa nie widzą.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/9.jpg"),
    question: "Czy koty angażują się w politykę?",
    answer1: "Tak, Kotem zaangażowanym politycznie był kot Stubbs.",
    answer2: "Tak, Kotem zaangażowanym politycznie był kot Mruczek.",
    answer3: "Nie.",
    buttonText: "Następne pytanie",
    quriosity:
      "W mieście Talkeetna na Alasce, stanowisko burmistrza przez 20 lat obejmował kot. Został burmistrzem ponieważ, żaden inny kandydat nie przypadł do gustu mieszkańcom.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/10.jpg"),
    question: "Ile powiek ma kot?",
    answer1: "Dwie",
    answer2: "Trzy",
    answer3: "Cztery",
    buttonText: "Następne pytanie",
    quriosity:
      "Trzecia powieka stanowi maleńki trójkącik różowawej lub białawej tkanki, zazwyczaj widoczny w rogu oku.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/11.jpg"),
    question: "Ile wąsów ma kot po obu stronach pyszczka?",
    answer1: "10",
    answer2: "12",
    answer3: "14",
    buttonText: "Następne pytanie",
    quriosity:
      "Kot używa swoich wąsów, aby sprawdzić szerokość przejścia i czy się w nim zmieści.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/12.jpg"),
    question: "Które koty są przeważnie głuche?",
    answer1: "Czrne koty z żółtymi oczami",
    answer2: "Szare koty z żółtymi oczami",
    answer3: "Białe koty z niebieskimi oczami",
    buttonText: "Następne pytanie",
    quriosity:
      "Białe koty które mają tylko jedno oko niebieskie są głuche na to uch które znajduje się po stronie niebieskiego oka.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/13.jpg"),
    question: "Na jaką odległość widzą koty?",
    answer1: "Na odległość 30 metrów.",
    answer2: "Na odległość 36 metrów",
    answer3: "Na odległość 42 metrów",
    buttonText: "Następne pytanie",
    quriosity: "Dodatkowo, kąt widzenia kota wynosi ok 185 stopni.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/14.jpg"),
    question: "Ile lat mogą żyć koty?",
    answer1: "Do 20 lat.",
    answer2: "Do 30 lat.",
    answer3: "Do 40 lat.",
    buttonText: "Następne pytanie",
    quriosity: "Odpowiada to 98 ludzkim latom.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/15.jpg"),
    question: "Z jaką prędkością mruczą koty?",
    answer1: "Z prędkością z jaką pracuje silnik diesla.",
    answer2: "Z prędkością z jaką pracuje silnik traktora.",
    answer3: "Z prędkością z jaką pracuje silnik motocykla.",
    buttonText: "Następne pytanie",
    quriosity:
      "Średnio koty spędzają na mruczeniu ok 10 950 godzin. Koty mogą mruczeć zarówno podczas wdychania i wydychania powietrza.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/16.jpg"),
    question: "Czy Koty widzą w całkowitych ciemnościach?",
    answer1: "Tak",
    answer2: "Nie",
    answer3: "Tylko w gwieździste noce",
    buttonText: "Następne pytanie",
    quriosity:
      "Pomimo tego, iż koty przystosowują się do widzenia w niepełnym oświetleniu, to potrzebują 1/6 światła wymaganego dla ludzkiego oka.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/17.jpg"),
    question: "Jaka jest normalna temperatura dla kociego ciała?",
    answer1: "35-38 stopni Celsjusza.",
    answer2: "38-39 stopni Celsjusza.",
    answer3: "39-40 stopni Celsjusza.",
    buttonText: "Następne pytanie",
    quriosity:
      "Z tego powody koty zmuszone są szukać dodatkowego źródła ciepła.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/18.jpg"),
    question: "Ile ważył największy kot domowy?",
    answer1: "18,5 kg",
    answer2: "21,3 kg",
    answer3: "24,7 kg",
    buttonText: "Następne pytanie",
    quriosity:
      "Był to żyjący w  Australii kocur Himmy. Jego długość wynosiła prawie 1m.",
  },
  {
    id: question.length(),
    title: `{Pytanie ${id}}`,
    imageURL: require("../assets/19.jpg"),
    question: "Ile kotków może liczyć jeden poród?",
    answer1: "Od jednego do pięciu kotków.",
    answer2: "Od jednego do siedmiu kotków.",
    answer3: "Od jednego do dziewięciu kotków.",
    buttonText: "Następne pytanie",
    quriosity:
      "Największym zarejestrowanym porodem było 19 kotków. Niestety 4 z nich nie przeżyło.",
  },
];
